version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: source/conf.py

formats:
  - pdf
  - epub

python:
  install:
    - method: pip
      packages:
        - sphinx>=8.2
        - breathe
        - sphinx-rtd-theme