ethernet.c
const char* TAG
esp_netif_t* eth_netif
Referenced by ethernet_get_ip, ethernet_init, ethernet_set_static_ip.
esp_eth_handle_t eth_handle
Referenced by ethernet_event_handler, ethernet_init, ethernet_start, ethernet_stop.
bool ethernet_connected
Referenced by ethernet_event_handler, ethernet_is_connected, ethernet_stop, got_ip_event_handler.
void ethernet_event_handler(void *arg, esp_event_base_t event_base, int32_t event_id, void *event_data)
Event handler for Ethernet events.
arg Event handler argument event_base Event base event_id Event ID event_data Event data This function handles Ethernet events such as connection status changes It logs the events and updates the connection status Ernesto Estrada July 2, 2025 1.0
References eth_handle, ethernet_connected, TAG.
Referenced by ethernet_init.
static void got_ip_event_handler(void *arg, esp_event_base_t event_base, int32_t event_id, void *event_data)
References ethernet_connected, TAG.
Referenced by ethernet_init.
esp_err_t ethernet_init(void)
Initialize the W5500 Ethernet module.
Sets up SPI communication and initializes the W5500 chip esp_err_t ESP_OK on success, error code otherwise This function must be called before starting the Ethernet connection Ernesto Estrada July 2, 2025 1.0
References eth_handle, eth_netif, ethernet_event_handler, got_ip_event_handler, TAG, W5500_CS_GPIO, W5500_MISO_GPIO, W5500_MOSI_GPIO, W5500_RST_GPIO, W5500_SCLK_GPIO, W5500_SPI_HOST.
Referenced by system_init.
esp_err_t ethernet_start(void)
Start the Ethernet connection.
Starts the Ethernet interface and begins network connectivity esp_err_t ESP_OK on success, error code otherwise This function should be called after ethernet_init() Ernesto Estrada July 2, 2025 1.0
References eth_handle, TAG.
Referenced by system_init.
esp_err_t ethernet_stop(void)
Stop the Ethernet connection.
Stops the Ethernet interface esp_err_t ESP_OK on success, error code otherwise This function should be called to cleanly stop the Ethernet connection Ernesto Estrada July 2, 2025 1.0
References eth_handle, ethernet_connected, TAG.
bool ethernet_is_connected(void)
Check if Ethernet is connected.
true if connected, false otherwise This function checks the current connection status of the Ethernet interface This function can be used to determine if the Ethernet connection is active Ernesto Estrada July 2, 2025 1.0
References ethernet_connected.
Referenced by ethernet_monitor_task.
esp_err_t ethernet_get_ip(char *ip_str)
Get the IP address assigned to the Ethernet interface.
ip_str Buffer to store the IP address string (minimum 16 bytes) esp_err_t ESP_OK on success, error code otherwise This function retrieves the current IP address of the Ethernet interface The IP address is returned in standard dotted-decimal format Ernesto Estrada July 2, 2025 1.0
References eth_netif.
Referenced by ethernet_monitor_task.
esp_err_t ethernet_set_static_ip(void)
Configure static IP settings for the Ethernet interface.
Sets up static IP configuration instead of DHCP esp_err_t ESP_OK on success, error code otherwise This function should be called after ethernet_init() but before ethernet_start() Ernesto Estrada July 2, 2025 1.0
References eth_netif, STATIC_GATEWAY_ADDR, STATIC_IP_ADDR, STATIC_NETMASK_ADDR, TAG.
Referenced by system_init.