nvs_manager.h
NAMESPACE
Referenced by init_nvs_manager, save_int_to_nvs.
KEY_NVS_INIT
Referenced by init_nvs_manager.
KEY_OP_MIN
Referenced by init_nvs_manager, operation_time.
KEY_OP_HOURS
Referenced by init_nvs_manager, operation_time.
KEY_BOOT_COUNTER
Referenced by init_nvs_manager.
KEY_SYS_LANGUAGE
Referenced by init_nvs_manager, received_data.
KEY_SYS_COLOR
Referenced by init_nvs_manager, received_data.
KEY_MAINTENANCE_MIN
Referenced by init_nvs_manager, operation_time.
KEY_MAINTENANCE_HOURS
Referenced by init_nvs_manager, operation_time.
KEY_NUMBER_OF_MAINTENANCES
Referenced by init_nvs_manager.
void init_nvs_manager()
Initializes the NVS (Non-Volatile Storage).
This function initializes the NVS system, allowing for data storage and retrieval. This function should be called before using any NVS functions. Ernesto Estrada May 5, 2025 1.0
References boot_count, KEY_BOOT_COUNTER, KEY_MAINTENANCE_HOURS, KEY_MAINTENANCE_MIN, KEY_NUMBER_OF_MAINTENANCES, KEY_NVS_INIT, KEY_OP_HOURS, KEY_OP_MIN, KEY_SYS_COLOR, KEY_SYS_LANGUAGE, maintenance_hours, maintenance_minutes, NAMESPACE, number_of_maintenances, operation_hours, operation_minutes, system_color, system_language, TAG.
Referenced by init_nvs.
void save_int_to_nvs(const char *key, int32_t value)
Loads an integer value from NVS using the specified key.
key The key associated with the integer value in NVS. value int32_t variable to store the loaded value. This function does not return a value. Instead, it updates the global variable associated with the key. Make sure that all keys used in this function are defined in the NVS namespace. Ernesto Estrada June 16, 2025 1.0
References NAMESPACE.
Referenced by operation_time, received_data.