pages.h
Pages
Pages current_page
Variable to store the current page number.
Referenced by received_data, ui_task, update_header.
void main_page(void)
Function to handle the main page UI. This function is called when the current page is set to MAIN.
This function should contain the logic to update the main page of the Nextion display. It may include updating text fields, images, and other UI elements specific to the main page. This function does not return any value. this function is part of the ui_task and is called when the task is running and the current page is set to MAIN. ui_task Ernesto Estrada June 6, 2025 1.0 Ensure that the Nextion display is initialized before calling this function. This function should not be called directly, it is called by the ui_task.
References print_sensor_data.
Referenced by ui_task.
void main_menu_page(void)
Function to handle the main menu page UI. This function is called when the current page is set to MAIN_MENU.
This function should contain the logic to update the main menu page of the Nextion display. It may include updating text fields, images, and other UI elements specific to the main menu page. This function does not return any value. this function is part of the ui_task and is called when the task is running and the current page is set to MAIN_MENU. ui_task Ernesto Estrada June 6, 2025 1.0 Ensure that the Nextion display is initialized before calling this function. This function should not be called directly, it is called by the ui_task.
Referenced by ui_task.
void equipment_page(void)
Function to handle the equipment information page UI. This function is called when the current page is set to EQUIPMENT_INFO.
This function should contain the logic to update the equipment information page of the Nextion display. It may include updating text fields, images, and other UI elements specific to the equipment information page. This function does not return any value. this function is part of the ui_task and is called when the task is running and the current page is set to EQUIPMENT_INFO. ui_task Ernesto Estrada June 6, 2025 1.0 Ensure that the Nextion display is initialized before calling this function. This function should not be called directly, it is called by the ui_task.
Referenced by ui_task.
void module_page(void)
Function to handle the module information page UI. This function is called when the current page is set to MODULE_INFO.
This function should contain the logic to update the module information page of the Nextion display. It may include updating text fields, images, and other UI elements specific to the module information page. This function does not return any value. this function is part of the ui_task and is called when the task is running and the current page is set to MODULE_INFO. ui_task Ernesto Estrada June 6, 2025 1.0 Ensure that the Nextion display is initialized before calling this function. This function should not be called directly, it is called by the ui_task.
Referenced by ui_task.
void login_page(void)
Function to handle the login page UI. This function is called when the current page is set to LOG_IN.
This function should contain the logic to update the login page of the Nextion display. It may include updating text fields, images, and other UI elements specific to the login page. This function does not return any value. this function is part of the ui_task and is called when the task is running and the current page is set to LOG_IN. ui_task Ernesto Estrada June 6, 2025 1.0 Ensure that the Nextion display is initialized before calling this function. This function should not be called directly, it is called by the ui_task.
Referenced by ui_task.
void maintenance_page(void)
Function to handle the maintenance page UI. This function is called when the current page is set to MAINTENANCE.
This function should contain the logic to update the maintenance page of the Nextion display. It may include updating text fields, images, and other UI elements specific to the maintenance page. This function does not return any value. this function is part of the ui_task and is called when the task is running and the current page is set to MAINTENANCE. ui_task Ernesto Estrada June 6, 2025 1.0 Ensure that the Nextion display is initialized before calling this function. This function should not be called directly, it is called by the ui_task.
Referenced by ui_task.
void language_page(void)
Function to handle the language selection page UI. This function is called when the current page is set to LANGUAGE.
This function should contain the logic to update the language selection page of the Nextion display. It may include updating text fields, images, and other UI elements specific to the language selection page. This function does not return any value. this function is part of the ui_task and is called when the task is running and the current page is set to LANGUAGE. ui_task Ernesto Estrada June 6, 2025 1.0 Ensure that the Nextion display is initialized before calling this function. This function should not be called directly, it is called by the ui_task.
Referenced by ui_task.
void config_menu_page(void)
Function to handle the configuration menu page UI. This function is called when the current page is set to CONFIG_MENU.
This function should contain the logic to update the configuration menu page of the Nextion display. It may include updating text fields, images, and other UI elements specific to the configuration menu page. This function does not return any value. this function is part of the ui_task and is called when the task is running and the current page is set to CONFIG_MENU. ui_task Ernesto Estrada June 6, 2025 1.0 Ensure that the Nextion display is initialized before calling this function. This function should not be called directly, it is called by the ui_task.
Referenced by ui_task.
void control_page(void)
Function to handle the control page UI. This function is called when the current page is set to CONTROL.
This function should contain the logic to update the control page of the Nextion display. It may include updating text fields, images, and other UI elements specific to the control page. This function does not return any value. this function is part of the ui_task and is called when the task is running and the current page is set to CONTROL. ui_task Ernesto Estrada June 6, 2025 1.0 Ensure that the Nextion display is initialized before calling this function. This function should not be called directly, it is called by the ui_task.
Referenced by ui_task.
void service_page(void)
Function to handle the service page UI. This function is called when the current page is set to SERVICE.
This function should contain the logic to update the service page of the Nextion display. It may include updating text fields, images, and other UI elements specific to the service page. This function does not return any value. this function is part of the ui_task and is called when the task is running and the current page is set to SERVICE. ui_task Ernesto Estrada June 6, 2025 1.0 Ensure that the Nextion display is initialized before calling this function. This function should not be called directly, it is called by the ui_task.
Referenced by ui_task.
void machine_page(void)
Function to handle the machine page UI. This function is called when the current page is set to MACHINE.
This function should contain the logic to update the machine page of the Nextion display. It may include updating text fields, images, and other UI elements specific to the machine page. This function does not return any value. this function is part of the ui_task and is called when the task is running and the current page is set to MACHINE. ui_task Ernesto Estrada June 6, 2025 1.0 Ensure that the Nextion display is initialized before calling this function. This function should not be called directly, it is called by the ui_task.
Referenced by ui_task.
void system_page(void)
Function to handle the system page UI. This function is called when the current page is set to SYSTEM.
This function should contain the logic to update the system page of the Nextion display. It may include updating text fields, images, and other UI elements specific to the system page. This function does not return any value. this function is part of the ui_task and is called when the task is running and the current page is set to SYSTEM. ui_task Ernesto Estrada June 6, 2025 1.0 Ensure that the Nextion display is initialized before calling this function. This function should not be called directly, it is called by the ui_task.
Referenced by ui_task.
void about_page(void)
Function to handle the about page UI. This function is called when the current page is set to ABOUT.
This function should contain the logic to update the about page of the Nextion display. It may include updating text fields, images, and other UI elements specific to the about page. This function does not return any value. this function is part of the ui_task and is called when the task is running and the current page is set to ABOUT. ui_task Ernesto Estrada June 6, 2025 1.0 Ensure that the Nextion display is initialized before calling this function. This function should not be called directly, it is called by the ui_task.
Referenced by ui_task.
void system_events_page(void)
Function to handle the system events page UI. This function is called when the current page is set to SYSTEM_EVENTS.
This function should contain the logic to update the system events page of the Nextion display. It may include updating text fields, images, and other UI elements specific to the system events page. This function does not return any value. this function is part of the ui_task and is called when the task is running and the current page is set to SYSTEM_EVENTS. ui_task Ernesto Estrada June 6, 2025 1.0 Ensure that the Nextion display is initialized before calling this function. This function should not be called directly, it is called by the ui_task.
Referenced by ui_task.
void no_page(void)
Function to handle the case when no page is set. This function is called when the current page is set to NO_PAGE.
This function should contain the logic to handle the case when no specific page is set in the Nextion display. It may include clearing the display or showing a default message. This function does not return any value. this function is part of the ui_task and is called when the task is running and the current page is set to NO_PAGE. ui_task Ernesto Estrada June 6, 2025 1.0 Ensure that the Nextion display is initialized before calling this function. This function should not be called directly, it is called by the ui_task.