sensors.c
PRESSURE1_CH
Referenced by sensors_init, sensors_read.
PRESSURE2_CH
Referenced by sensors_init, sensors_read.
TEMP_PT1000_CH
Referenced by sensors_init, sensors_read.
ADC_ATTEN
Referenced by sensors_init.
ADC_WIDTH
Referenced by sensors_init.
ADC_REF_VOLTAGE
Referenced by sensors_read.
ADC_MAX_VALUE
Referenced by sensors_read.
SHUNT_RESISTOR_OHMS
Referenced by sensors_read.
R_FIXED_OHMS
Referenced by sensors_read.
sensor_data_t latest_sensor_data
Referenced by sensors_get_latest, sensors_read.
SemaphoreHandle_t sensor_data_mutex
Referenced by sensors_get_latest, sensors_init, sensors_read.
const char* TAG
adc_oneshot_unit_handle_t adc1_handle
Referenced by sensors_init, sensors_read.
esp_err_t sensors_init(void)
Initialize the sensors. This function sets up the ADC channels for reading pressure and temperature sensors. It should be called before any sensor readings are performed.
ESP_OK on success, or an error code on failure. Ernesto Estrada June 10, 2025 1.0
References adc1_handle, ADC_ATTEN, ADC_WIDTH, PRESSURE1_CH, PRESSURE2_CH, sensor_data_mutex, TEMP_PT1000_CH.
Referenced by system_init.
esp_err_t sensors_read(sensor_data_t *data)
Read sensor data. This function reads the current values from the pressure and temperature sensors. It populates the provided sensor_data_t structure with the latest readings.
data Pointer to a sensor_data_t structure where the sensor readings will be stored. ESP_OK on success, or an error code on failure. Ernesto Estrada June 10, 2025 1.0 The function assumes that sensors_init() has been called successfully before this function. It will read the ADC values, convert them to pressure and temperature, and store them in the provided structure.
References adc1_handle, ADC_MAX_VALUE, ADC_REF_VOLTAGE, latest_sensor_data, PRESSURE1_CH, sensor_data_t::pressure1_mbar, PRESSURE2_CH, sensor_data_t::pressure2_mbar, R_FIXED_OHMS, sensor_data_mutex, SHUNT_RESISTOR_OHMS, system_state, TEMP_PT1000_CH, sensor_data_t::temperature_C, update_system_status.
Referenced by sensor_task.
esp_err_t sensors_get_latest(sensor_data_t *data)
References latest_sensor_data, sensor_data_mutex.
Referenced by print_sensor_data.