serial_send.c
SemaphoreHandle_t uart_mutex
Referenced by uart_send_command, uart_send_init.
void uart_send_init(void)
Add mutex initialization for UART communication.
This function initializes a mutex to ensure thread-safe access to the UART communication. This function does not return any value. This function should be called after initializing the UART and before any UART communication. Ernesto Estrada June 10, 2025 1.0
References uart_mutex.
Referenced by system_init.
void uart_send_command(const char *cmd)
Sends the termination command to the Nextion display.
This function sends the termination command xFF xFF xFF to the Nextion display to indicate the end of a command. This function does not return any value. Ernesto Estrada. June 9, 2025. 1.0
References END_COMMAND, uart_mutex, UART_PORT_NUM.
Referenced by send_float_to_display, send_global_object, send_int_to_display, send_method_to_display, send_text_to_display.
void send_int_to_display(const char *object, const char *attribute, int value)
Sends a command to update an integer attribute of an object on the Nextion display.
page Const char pointer containing the page name. object Const char pointer containing the object name. attribute Const char pointer containing the attribute name to be updated. value Integer value to set the attribute to. This function constructs a command string to update an integer attribute of a specified object on the Nextion display. This function does not return any value. Ernesto Estrada. June 9, 2025. 1.0
References uart_send_command.
Referenced by update_header.
void send_float_to_display(const char *page, const char *object, const char *attribute, float value, int precision)
Sends a command to update a float attribute of an object on the Nextion display with precision.
page Const char pointer containing the page name. object Const char pointer containing the object name. attribute Const char pointer containing the attribute name to be updated. value Float value to set the attribute to. precision Integer vaLue indicating the number of decimal places to format the float value. This function constructs a command string to update a float attribute of a specified object on the Nextion display, with a specified number of decimal places. This function does not return any value. Ernesto Estrada. June 9, 2025. 1.0
References uart_send_command.
Referenced by print_sensor_data.
void send_text_to_display(const char *page, const char *object, const char *attribute, const char *text)
Sends a command to update a text attribute of an object on the Nextion display.
page Const char pointer containing the page name. object Const char pointer containing the object name. attribute Const char pointer containing the attribute name to be updated. text Const char pointer conatining the text string to be set as the attribute value. This function constructs a command string to update a text attribute of a specified object on the Nextion display. This function does not return any value. Ernesto Estrada. June 9, 2025. 1.0
References uart_send_command.
Referenced by print_operation_time, print_sensor_data.
void send_method_to_display(const char *page, const char *object, const char *method)
Sends a method call to an object on the Nextion display.
page Const char pointer containing the page name. object Const char pointer containing the object namne. method Const char pointer containig the method name to be called. This function constructs a command string to call a method on a specified object on the Nextion display. This function does not return any value. Ernesto Estrada. june 9, 2025. 1.0
References uart_send_command.
Referenced by store_system_event.
void send_global_object(const char *object, const char *attribute, const char *value)
Sends a command to update a global object attribute on the Nextion display.
object const char pointer containing the global object name. attribute const char pointer containing the attribute name to be updated. value const char pointer containing the value to be set as the attribute value. This function constructs a command string to update a global object attribute on the Nextion display. This function does not return any value. Ernesto Estrada. June 9, 2025. 1.0
References uart_send_command.
Referenced by ethernet_monitor_task, update_date_task, update_header, update_time_task.