setup.h
UART_PORT_NUM
Referenced by display_ready, init_uart, serial_read, uart_send_command, wait_for_datetime.
UART_BAUD_RATE
Referenced by init_uart.
UART_TX_PIN
UART_RX_PIN
END_COMMAND
Referenced by uart_send_command.
void init_uart()
Initializes the serial communication.
This function sets up the UART(Universal Asynchronous Receiver-Transmitter). This function should be called before using any serial communication functions. Ernesto Estrada May 5, 2025 1.0
References UART_BAUD_RATE, UART_PORT_NUM.
Referenced by system_init.
void init_nvs()
Initializes the NVS (Non-Volatile Storage).
This function initializes the NVS system, allowing for data storage and retrieval. This function does not return any value. This function should be called before attempting to read or write any data to NVS. Ernesto Estrada May 6, 2025
References init_nvs_manager.
Referenced by system_init.
void display_ready(void)
Waits for the Nextion display to send the command indicating that it is ready.
This function blocks until the display sends the command: 0x88, 0xFF, 0xFF, 0xFF This function should be called right after the initialization of the UART and NVS. Ernesto Estrada. June 6, 2025. 1.0
References system_color, system_language, UART_PORT_NUM.
Referenced by system_init.
void wait_for_datetime(void)
Blocks until a valid date/time string is received via UART.
The expected string format is p00,MM,HH,DD,MM,YYYY followed by three 0xFF bytes. Ensure that the Nextion display is properly configured to send the date and time in the expected format. This function should be called before starting any FreeRTOS tasks. Ernesto Estrada June 5, 2025 1.0
References set_system_time, UART_PORT_NUM.
Referenced by system_init.