system.c
int32_t system_state
Integer to store the system's state.
0 = Normal, 1 = Warning, 2 = Alarm. This variable is used to track the current state of the system based on sensor readings and operational conditions.
Referenced by sensors_read, update_header, update_system_status.
int32_t operation_minutes
Integer to store the system's operation time in minutes since the last reboot.
Referenced by init_nvs_manager, operation_time, received_data.
int32_t operation_hours
Integer to store the system's operation time in hours since the last reboot.
Referenced by init_nvs_manager, operation_time, received_data.
int32_t boot_count
Integer to keep track of the number of system reboots.
Referenced by init_nvs_manager.
int32_t system_language
Integer to store the system's language.
0 = English, 1 = Spanish, 2 = Portuguese, 3 = French, 4 = German.
Referenced by display_ready, format_current_date, init_nvs_manager, received_data, update_date_task, update_header.
int32_t system_color
Integer to store the system's color.
0 = Light mode, 1 = Dark mode.
Referenced by display_ready, get_status_attributes, init_nvs_manager, received_data.
int32_t maintenance_minutes
Integer to store the minutes the system has been in operation since commissioning.
This variable is used to track the minutes of operation for maintenance purposes.
Referenced by init_nvs_manager, operation_time.
int32_t maintenance_hours
Integer to store the hours the system has been in operation since commissioning.
This variable is used to track the hours of operation for maintenance purposes.
Referenced by init_nvs_manager, operation_time.
int32_t number_of_maintenances
Integer to store the number of maintenances performed.
Referenced by init_nvs_manager.
bool acknowledged
Boolean to indicate if the user has acknowledged a warning or alarm.
This variable is used to track if the user has acknowledged a warning or alarm in the system.
Referenced by update_system_status.
bool warning_or_alarm_occurred
Boolean to indicate if a warning or alarm has occurred.
This variable is used to track if any warning or alarm has occurred in the system. It is set to true when a warning or alarm is triggered and can be used to display notifications or alerts.
Referenced by update_system_status.
bool warning_or_alarm_active
Boolean to indicate if a warning or alarm is currently active.
This variable is used to track if a warning or alarm is currently active in the system. It is set to true when a warning or alarm is acknowledged and can be used to control the display of notifications or alerts.
Referenced by update_system_status.
int attributes[4][4]
Array of integers to store the values of the header components.
This array is used to store the values of the header components such as title color, status color, slider picture, and icon state. It is used to update the header display on the Nextion screen based on the current system state.
Referenced by update_header.
int operation_seconds
Referenced by operation_time.
void system_init(void)
Initializes the system.
This function initializes the system by setting up the necessary components such as UART, NVS, and display. It also waits for the Nextion display to be ready and for a valid date/time string to be received. This function should be called at the beginning of the main application to ensure all components are ready for use. Ernesto Estrada June 16, 2025 1.0
References display_ready, ethernet_init, ethernet_set_static_ip, ethernet_start, init_nvs, init_uart, sensors_init, uart_send_init, wait_for_datetime.
Referenced by app_main.
void operation_time(void)
Updates the operation time.
This function updates the operation time by incrementing the seconds, minutes, and hours based on the system's uptime. It also handles the rollover of seconds to minutes and minutes to hours. This function does not return any value. This function should be called periodically to keep track of the system's operation time. Ernesto Estrada June 16, 2025 1.0
References KEY_MAINTENANCE_HOURS, KEY_MAINTENANCE_MIN, KEY_OP_HOURS, KEY_OP_MIN, maintenance_hours, maintenance_minutes, operation_hours, operation_minutes, operation_seconds, save_int_to_nvs.
Referenced by operation_time_task.
void store_system_event(int type, int sensor_index)
Stores a system event in the event log.
type The type of event to store (e.g., 0 for normal, 1 for warning, 2 for alarm). sensor_index The index of the sensor that triggered the event (0 for pressure sensor 1, 1 for pressure sensor 2, 2 for temperature sensor). This function logs the event type and the sensor index that triggered the event. It is used to keep track of system events for diagnostics and monitoring purposes. This function should be called whenever a significant event occurs in the system, such as a warning or alarm condition. Ernesto Estrada June 19, 2025 1.0 Ensure that the sensor_index is valid (0, 1, or 2) to avoid out-of-bounds access.
References get_event_timestamp, send_method_to_display.
Referenced by update_system_status.
int32_t update_system_status(sensor_data_t *data)
Updates the system status based on sensor data.
data Pointer to the sensor_data_t structure containing the latest sensor readings. This function updates the global system state based on the provided sensor data. It checks the pressure and temperature readings to determine if the system is in a normal, warning, or alarm state. It also updates the acknowledged status and warning/alarm flags based on the sensor readings. Returns an integer indicating the system state: 0: Normal 1: Warning 2: Alarm This function should be called whenever new sensor data is available to keep the system status updated. Ernesto Estrada June 17, 2025 1.0
References acknowledged, sensor_data_t::pressure1_mbar, sensor_data_t::pressure2_mbar, store_system_event, system_state, sensor_data_t::temperature_C, warning_or_alarm_active, warning_or_alarm_occurred.
Referenced by sensors_read.
void update_header(void)
Updates the header on the Nextion display.
This function updates the header on the Nextion display to reflect the current system state. It updates the title color, status color, slider picture, and icon state based on the system state. This function should be called whenever the system state changes or periodically to keep the display updated. Ernesto Estrada June 18, 2025 1.0 This function should not be called directly; it is intended to be used as a FreeRTOS task or called from the main application loop.
References attributes, current_page, get_status_attributes, get_status_text, MAIN, send_global_object, send_int_to_display, system_language, system_state.
Referenced by status_update_task.