tasks.h
void serial_read_task(void *pvParameters)
Wrapper function for the serial read task.
This function is called from the FreeRTOS task scheduler. pvParameters Pointer to task parameters. This function does not return any value. It is designed to be used as a FreeRTOS task, which continuously reads data from the serial port. Ernesto Estrada. June 6, 2025. 1.0 This function should not be called directly; it is intended to be used as a FreeRTOS task.
References serial_read.
Referenced by app_main.
void operation_time_task(void *pvParameters)
Wrapper function for the operation time task.
This function is called from the FreeRTOS task scheduler. pvParameters Pointer to task parameters. This function does not return any value. It is designed to be used as a FreeRTOS task, which updates the operation time of the system. Ernesto Estrada. June 16, 2025. 1.0 This function should not be called directly;
References operation_time.
Referenced by app_main.
void update_date_task(void *pvParamerters)
Wrapper function for the update date task.
This function is called fromt the FreeRTOS task scheduler. pvParameters Pointer to task parameters. This function does not return any value. Ernesto Estrada. June 6, 2025. 1.0 This function should not be called directly; it is intended to be used as a FreeRTOS task.
References format_current_date, send_global_object, system_language.
Referenced by app_main.
void update_time_task(void *pvpParameters)
Wrapper function for the update time task.
This function is called from the FreeRTOS task scheduler. pvParameters Pointer to task parameters. This function does not return any value. Ernesto Estrada. June 6, 2025. 1.0 This function should not be called directly; it is intended to be used as a FreeRTOS task.
References format_current_time, send_global_object.
Referenced by app_main.
void sensor_task(void *pvParameters)
Wrapper function for the sensor task.
This function is called from the FreeRTOS task scheduler. pvParameters Pointer to task parameters. This function does not return any value. Ernesto Estrada. June 6, 2025. 1.0 This function should not be called directly; it is intended to be used as a FreeRTOS task.
References sensors_read.
Referenced by app_main.
void status_update_task(void *pvParameters)
Wrapper function for the status update task.
This function is called from the FreeRTOS task scheduler. pvParameters Pointer to task parameters. This function does not return any value. It is designed to update the system status based on sensor data and user interactions. Ernesto Estrada. June 18, 2025. 1.0 This function should not be called directly; it is intended to be used as a FreeRTOS task.
References update_header.
Referenced by app_main.
void ui_task(void *pvParameters)
Wrapper function for the UI task.
This function is called from the FreeRTOS task scheduler. pvParameters Pointer to task parameters. This function does not return any value. It is designed to handle user interface interactions and updates. Ernesto Estrada. June 6, 2025. 1.0 This function should not be called directly; it is intended to be used as a FreeRTOS task.
References ABOUT, about_page, CONFIG_MENU, config_menu_page, CONTROL, control_page, current_page, EQUIPMENT_INFO, equipment_page, LANGUAGE, language_page, LOG_IN, login_page, MACHINE, machine_page, MAIN, MAIN_MENU, main_menu_page, main_page, MAINTENANCE, maintenance_page, MODULE_INFO, module_page, NO_PAGE, SERVICE, service_page, SYSTEM, SYSTEM_EVENTS, system_events_page, system_page.
Referenced by app_main.
void ethernet_monitor_task(void *pvParameters)
Wrapper function for the ethernet monitoring task.
This function is called from the FreeRTOS task scheduler. pvParameters Pointer to task parameters. This function does not return any value. It is designed to monitor the ethernet connection status and handle reconnections. Ernesto Estrada. July 2, 2025. 1.0 This function should not be called directly; it is intended to be used as a FreeRTOS task.
References ethernet_get_ip, ethernet_is_connected, send_global_object, TAG.
Referenced by app_main.