time_manager.c
const char* hours_text[][]
Array containing the words for "hours" in different languages.
Referenced by print_operation_time.
const char* minutes_text[][]
Array containing the words for "minutes" in different languages.
Referenced by print_operation_time.
void set_system_time(int year, int month, int day, int hour, int min, int sec)
Initializes the time manager.
This function should be called inside the wait_for_datetime() function. This function sets up the system time based on the provided date and time from the Nextion display. year Full year (e.g., 2025) month Month (1-12) day Day of the month (1-31) hour Hour of the day (0-23) min Minute of the hour (0-59) Ernesto Estrada June 6, 2025 1.0
Referenced by wait_for_datetime.
const char * format_current_time(void)
Formats the current time as a string in 12-hour format with AM/PM.
This function returns a pointer to a static string, so it should not be modified or freed. A pointer to a static string containing the formatted time (e.g., "02:30pm"). Ernesto Estrada June 6, 2025 1.0
Referenced by update_time_task.
const char * format_current_date(int language)
Formats the current date as a string.
language Integer representing the system language: 0: English -1: Spanish -2: Portuguese -3: French -4: German This function returns a pointer to a static string, so it should not be modified or freed. A pointer to a static string containing the formatted date according to the system language selected. Ernesto Estrada June 6, 2025 1.0
References get_day_of_week, get_month_name, system_language.
Referenced by update_date_task.
void print_operation_time(int hours, int minutes, int32_t language)
Prints the current operation time to the console.
This function does not return any value. This function prints the operation time in the format "HH:MM" to the console. It is useful for debugging and monitoring the system's operation time. Ernesto Estrada June 19, 2025 1.0
References hours_text, minutes_text, send_text_to_display.
Referenced by received_data.
const char * get_event_timestamp(void)
Gets the current event timestamp.
This function returns a pointer to a static string containing the current event timestamp. The timestamp is formatted as "YYYY-MM-DD HH:MM:SS". The returned string is static and should not be modified or freed. A pointer to a static string containing the current event timestamp. Ernesto Estrada June 19, 2025 1.0
Referenced by store_system_event.