utils.h
void print_sensor_data(void)
Prints the data from the sensors. This function retrieves the latest sensor data and prints it to the console.
This function does not return any value. Ernesto Estrada June 16, 2025 1.0
References sensor_data_t::pressure1_mbar, sensor_data_t::pressure2_mbar, send_float_to_display, send_text_to_display, sensors_get_latest, sensor_data_t::temperature_C.
Referenced by main_page.
void get_status_attributes(int32_t state, int status_attributes[4])
Updates the header to reflect the current system state. This function updates the header on the Nextion display to show the current system state.
system_state The current state of the system (0 = Normal, 1 = Warning, 2 = Alarm). status_attributes An array containing status attributes to be displayed in the header. The array should contain 6 elements representing different status indicators. This function does not return any value. Ernesto Estrada June 17, 2025 1.0
References system_color.
Referenced by update_header.
const char * get_status_text(int32_t state, int32_t language)
Retrieves the status text based on the current system state and language. This function returns a string representing the status text for the given state and language.
state The current state of the system (0 = Normal, 1 = Warning, 2 = Alarm). language The language code (0 = English, 1 = Spanish, 2 = Portuguese, 3 = French, 4 = German). A string containing the status text in the specified language. The function uses a switch-case structure to determine the appropriate status text based on the state and language. Ernesto Estrada June 18, 2025 1.0
Referenced by update_header.